version: '2'
services:
  lb:
    image: dockercloud/haproxy:1.2
    ports:
      # HOST:CONTAINER
      - '80:80'    
    links:
      - web
    volumes:
      # HOST:CONTAINER
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BALANCE: roundrobin
      VIRTUAL_HOST: dockermeetup.dev

  web:
    restart: always
    dns:
      - 8.8.8.8
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: web/.env
    # environment:
    #   DATABASE_USER: root
    #   DATABASE_PASS: password
    #   DATABASE_HOST: db
    #   DATABASE_NAME: dev-db
    #   GIN_MODE: debug
    #   HTTP_PORT: 8080
    expose:
      - "8080"
    links:
    # depends_on
      - database:db

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: "dev-db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

# networks:
#   app_net:
#     driver: bridge
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
#     ipam:
#       driver: default
#       config:
#       - subnet: 172.16.238.0/24
#         gateway: 172.16.238.1
#       - subnet: 2001:3984:3989::/64
#         gateway: 2001:3984:3989::1
