version: '2'
services:
  lb:
    image: dockercloud/haproxy:1.2
    ports:
      - '80:80'    
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BALANCE: roundrobin
      VIRTUAL_HOST: dockermeetup.dev

  web:
    extends:
        file: common-services.yml
        service: web
    environment:
        - GIN_MODE=debug
        - DATABASE_NAME=prod-db
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    links:
      - database:db

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: "prod-db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"