# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c77d46b4c9b344e27c7768c920a4fe8624f80a403a50c573ecfe9415c7b88fb2801bfad0fbb9eb4d63c0dfece11113d1f7510f54effbd7a2fa6414c9bfda03e

test:
  secret_key_base: 870cd0172bc571503dc2f168df9ef4dded7763375139a85ce8df19c723034acb27d5793fc9440211fd7eca114ad109042d7c0cdb528bd4caa4234487797d8434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
